"use client";

import { motion } from "framer-motion";
import { Brain, Cpu, Sparkles } from "lucide-react";
import type { AIEngineMeta } from "@/lib/ai/types";
import MatchedSignals from "./MatchedSignals";

interface AIEngineBadgeProps {
  engine: AIEngineMeta | null;
  loading?: boolean;
}

export default function AIEngineBadge({ engine, loading }: AIEngineBadgeProps) {
  if (loading) {
    return (
      <motion.div
        className="glass-card mb-4 rounded-2xl border border-atlas-primary/30 p-4"
        animate={{ opacity: [0.5, 1, 0.5] }}
        transition={{ duration: 1.5, repeat: Infinity }}
      >
        <div className="flex items-center gap-3">
          <Cpu className="h-5 w-5 animate-pulse text-atlas-cyan" />
          <p className="text-sm text-atlas-muted">
            TaliinAtlas Custom ML Engine is generating your atlas...
          </p>
        </div>
      </motion.div>
    );
  }

  if (!engine) return null;

  const categoryLabel = engine.category
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="glass-card mb-4 rounded-2xl border border-atlas-cyan/25 bg-gradient-to-r from-atlas-primary/10 via-atlas-card/80 to-atlas-cyan/10 p-4"
    >
      <div className="flex flex-wrap items-start gap-3">
        <motion.div className="flex h-10 w-10 items-center justify-center rounded-xl border border-atlas-primary/40 bg-atlas-primary/15">
          <Brain className="h-5 w-5 text-atlas-primary" />
        </motion.div>
        <div className="min-w-0 flex-1">
          <p className="flex items-center gap-1 text-xs font-medium uppercase tracking-wider text-atlas-cyan">
            <Sparkles className="h-3.5 w-3.5" />
            Generated by TaliinAtlas Custom ML Engine
          </p>
          <p className="mt-1 text-sm text-atlas-text">
            Detected: <span className="font-semibold text-atlas-primary">{categoryLabel}</span>
            {" · "}
            Confidence:{" "}
            <span className="font-semibold text-atlas-completed">
              {Math.round(engine.confidence * 100)}%
            </span>
          </p>
          <p className="mt-0.5 text-xs text-atlas-muted">
            Provider: Local custom ML · Model v{engine.modelVersion} · No paid API
          </p>
          <MatchedSignals signals={engine.matchedSignals} className="mt-2" />
        </div>
      </div>
    </motion.div>
  );
}
